// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addMerchantProductStmt, err = db.PrepareContext(ctx, addMerchantProduct); err != nil {
		return nil, fmt.Errorf("error preparing query AddMerchantProduct: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getAllMerchantProductsStmt, err = db.PrepareContext(ctx, getAllMerchantProducts); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllMerchantProducts: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUsersStmt, err = db.PrepareContext(ctx, getUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsers: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.updateUserToMerchantStmt, err = db.PrepareContext(ctx, updateUserToMerchant); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserToMerchant: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addMerchantProductStmt != nil {
		if cerr := q.addMerchantProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMerchantProductStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getAllMerchantProductsStmt != nil {
		if cerr := q.getAllMerchantProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllMerchantProductsStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUsersStmt != nil {
		if cerr := q.getUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsersStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.updateUserToMerchantStmt != nil {
		if cerr := q.updateUserToMerchantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserToMerchantStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	addMerchantProductStmt     *sql.Stmt
	createUserStmt             *sql.Stmt
	deleteUserStmt             *sql.Stmt
	getAllMerchantProductsStmt *sql.Stmt
	getUserStmt                *sql.Stmt
	getUsersStmt               *sql.Stmt
	updateUserPasswordStmt     *sql.Stmt
	updateUserToMerchantStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		addMerchantProductStmt:     q.addMerchantProductStmt,
		createUserStmt:             q.createUserStmt,
		deleteUserStmt:             q.deleteUserStmt,
		getAllMerchantProductsStmt: q.getAllMerchantProductsStmt,
		getUserStmt:                q.getUserStmt,
		getUsersStmt:               q.getUsersStmt,
		updateUserPasswordStmt:     q.updateUserPasswordStmt,
		updateUserToMerchantStmt:   q.updateUserToMerchantStmt,
	}
}
