// Code generated by sqlc. DO NOT EDIT.
// source: merchant_query.sql

package postgres

import (
	"context"
)

const getMerchantID = `-- name: GetMerchantID :one
SELECT id FROM merchants
WHERE user_id = $1
`

func (q *Queries) GetMerchantID(ctx context.Context, userID int32) (int32, error) {
	row := q.queryRow(ctx, q.getMerchantIDStmt, getMerchantID, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
