// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"database/sql"
)

type Merchant struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	UserID int32  `json:"userID"`
}

type MerchantProduct struct {
	ID         int32 `json:"id"`
	ProductID  int32 `json:"productID"`
	MerchantID int32 `json:"merchantID"`
}

type Outlet struct {
	ID         int32         `json:"id"`
	MerchantID int32         `json:"merchantID"`
	UserID     sql.NullInt32 `json:"userID"`
}

type OutletProduct struct {
	ID        int32         `json:"id"`
	ProductID sql.NullInt32 `json:"productID"`
	OutletID  sql.NullInt32 `json:"outletID"`
}

type Product struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Image string `json:"image"`
	Sku   string `json:"sku"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
}
